# Uncomment this line to define a global platform for your project
  #platform :ios, '9.0'

target 'vmc_app' do

  # Pods for vmc_app
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'
  use_frameworks!
  pod 'Kingfisher', '~> 2.4'
  #pod 'SwiftHTTP', '~> 2.0.0'
  #pod 'Alamofire', '~> 4.0'
  pod 'Alamofire', '2.0.2'
end
